# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Uii.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/mw.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Windown = QtWidgets.QStackedWidget(self.centralwidget)
        self.Windown.setObjectName("Windown")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Home)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.Home)
        self.frame_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    image: url(:/newPrefix/mw.jpg);\n"
"}\n"
"Spacer{background-color: none;}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setStyleSheet("image: none;\n"
"background-color: none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMinimumSize(QtCore.QSize(125, 20))
        self.label_2.setStyleSheet("image: none;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.PageLiberarArara = QtWidgets.QPushButton(self.frame_5)
        self.PageLiberarArara.setMinimumSize(QtCore.QSize(125, 100))
        self.PageLiberarArara.setMaximumSize(QtCore.QSize(125, 100))
        self.PageLiberarArara.setFocusPolicy(QtCore.Qt.NoFocus)
        self.PageLiberarArara.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0, 0.7);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius: 20px;\n"
"}")
        self.PageLiberarArara.setObjectName("PageLiberarArara")
        self.verticalLayout.addWidget(self.PageLiberarArara)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("image: none;\n"
"background-color: none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setMinimumSize(QtCore.QSize(125, 20))
        self.label_3.setStyleSheet("image: none;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMinimumSize(QtCore.QSize(125, 100))
        self.pushButton_2.setMaximumSize(QtCore.QSize(125, 100))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0, 0.7);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setStyleSheet("image: none;\n"
"background-color: none;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMinimumSize(QtCore.QSize(125, 20))
        self.label_4.setStyleSheet("image: none;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setMinimumSize(QtCore.QSize(125, 100))
        self.pushButton_4.setMaximumSize(QtCore.QSize(70, 100))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0, 0.7);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setStyleSheet("image: none;\n"
"background-color: none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setMinimumSize(QtCore.QSize(125, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("image: none;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(125, 100))
        self.pushButton_3.setMaximumSize(QtCore.QSize(125, 100))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 170, 0, 0.7);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.frame_7)
        self.gridLayout_11.addWidget(self.frame_4, 0, 0, 1, 1)
        self.Windown.addWidget(self.Home)
        self.Arara = QtWidgets.QWidget()
        self.Arara.setObjectName("Arara")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Arara)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.Arara)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    image: url(:/newPrefix/mw.jpg);\n"
"}\n"
"Spacer{background-color: none;}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 7, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(100, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 3, 2, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(70, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 3, 0, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(600, 250))
        self.frame_3.setMaximumSize(QtCore.QSize(650, 200))
        self.frame_3.setStyleSheet("QFrame{\n"
"    image: none;\n"
"    border-radius: 10px;\n"
"    background-color: none;\n"
"}\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea.setStyleSheet("border-radius: 10px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.scrollAreaWidgetContents.setStyleSheet("border-radius: 10px;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelLiberarPdv = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelLiberarPdv.setFont(font)
        self.labelLiberarPdv.setMouseTracking(False)
        self.labelLiberarPdv.setFocusPolicy(QtCore.Qt.TabFocus)
        self.labelLiberarPdv.setStyleSheet("border-radius: 10px;")
        self.labelLiberarPdv.setText("")
        self.labelLiberarPdv.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLiberarPdv.setWordWrap(True)
        self.labelLiberarPdv.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelLiberarPdv.setObjectName("labelLiberarPdv")
        self.gridLayout_4.addWidget(self.labelLiberarPdv, 0, 1, 1, 1)
        self.labelLiberarArara = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelLiberarArara.setFont(font)
        self.labelLiberarArara.setStyleSheet("border-radius: 10px;")
        self.labelLiberarArara.setText("")
        self.labelLiberarArara.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLiberarArara.setWordWrap(True)
        self.labelLiberarArara.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelLiberarArara.setObjectName("labelLiberarArara")
        self.gridLayout_4.addWidget(self.labelLiberarArara, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 4, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(700, 200))
        self.frame_2.setStyleSheet("image: none;\n"
"border-radius: 10px;\n"
"background-color: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 1, 3, 1, 1)
        self.btnLiberarArara = QtWidgets.QPushButton(self.frame_2)
        self.btnLiberarArara.setMinimumSize(QtCore.QSize(200, 50))
        self.btnLiberarArara.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgba(85, 170, 255, 0.5);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btnLiberarArara.setObjectName("btnLiberarArara")
        self.gridLayout_5.addWidget(self.btnLiberarArara, 1, 2, 1, 1)
        self.inputCNPJ = QtWidgets.QLineEdit(self.frame_2)
        self.inputCNPJ.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputCNPJ.setFont(font)
        self.inputCNPJ.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"border-radius: 5px;")
        self.inputCNPJ.setObjectName("inputCNPJ")
        self.gridLayout_5.addWidget(self.inputCNPJ, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.checkSalvarCNPJ = QtWidgets.QCheckBox(self.frame_2)
        self.checkSalvarCNPJ.setEnabled(True)
        self.checkSalvarCNPJ.setMinimumSize(QtCore.QSize(20, 0))
        self.checkSalvarCNPJ.setMaximumSize(QtCore.QSize(100, 16777215))
        self.checkSalvarCNPJ.setObjectName("checkSalvarCNPJ")
        self.gridLayout_5.addWidget(self.checkSalvarCNPJ, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 3, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.Windown.addWidget(self.Arara)
        self.gridLayout.addWidget(self.Windown, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Windown.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Utilitario de automação"))
        self.label_2.setText(_translate("MainWindow", "ARARA             "))
        self.PageLiberarArara.setText(_translate("MainWindow", "Liberar Arara"))
        self.label_3.setText(_translate("MainWindow", "TextLabel             "))
        self.pushButton_2.setText(_translate("MainWindow", "Prox"))
        self.label_4.setText(_translate("MainWindow", "TextLabel             "))
        self.pushButton_4.setText(_translate("MainWindow", "Prox"))
        self.label_5.setText(_translate("MainWindow", "TextLabel             "))
        self.pushButton_3.setText(_translate("MainWindow", "Prox"))
        self.btnLiberarArara.setText(_translate("MainWindow", "Liberar"))
        self.label.setText(_translate("MainWindow", "CNPJ:"))
        self.checkSalvarCNPJ.setText(_translate("MainWindow", "Salvar"))
import bg_rc
